artificial_demo/api/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import store_dataset, Store_Data

urlpatterns = [
    path('upload_data/', Store_Data.as_view()),
]

artificial_demo/artificial_demo/urls.py
from django.contrib import admin
from django.urls import path,include
from webapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('artificial_demo/',include('webapp.urls')),
    path('api/', include('api.urls')),
]

artificial_demo/webapp/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import upload_file,reset_BankModel,list_dataset, train_evaluate,prediction_new,prediction_list

urlpatterns = [
    path('machine-learning/', upload_file, name="machine-learning" ),
    path('machine-learning/reset', reset_BankModel, name="reset"),
    path('machine-learning/train_evaluate', train_evaluate, name="train_evaluate"),
    path('machine-learning/predictions', prediction_list, name="predictions" ),
    path('machine-learning/predictions/new', prediction_new, name="prediction_new" ),
    path('list_dataset/', list_dataset),
]

artificial_demo/webapp/models.py
from django.db import models

class BankModel(models.Model):

    JOB=(
        ('management','management'), ('technician','technician'),
        ('entrepreneur','entrepreneur'), ('blue-collar','blue-collar'),
        ('unknown','unknown'), ('retired','retired'), ('admin.','admin.'),
        ('services','services'),('self-employed','self-employed'),('unemployed','unemployed'),
        ('housemaid','housemaid'),('student', 'student'),
    )
    MARTIAL= (
        ('married','married'),('single','single'), ('divorced','divorced'),
    )
    EDUCATION = (
        ('tertiary','tertiary'),('secondary','secondary'),('unknown','unknown'), (  'primary',  'primary'),
    )
    DEFAULT = (
        ('no','no'), ('yes','yes'),
    )
    HOUSING = (
        ('no','no'), ('yes','yes'),
    )
    LOAN = (
        ('no','no'), ('yes','yes'),
    )
    CONTACT=(
        ('unknown','unknown'),('cellular','cellular'),('telephone','telephone'),  
    )
    MONTH= (
        ('may','may'),('jun','jun'),('jul','jul'),('aug','aug'),('oct','oct'),('nov','nov'),
        ('dec','dec'),('jan','jan'),('feb','feb'),('mar','mar'),('apr','apr'),('sep','sep'),
    )
    POUTCOME = ( 
        ('unknown','unknown'),('failure','failure'),('other','other'), ('success','success')
    )
    Y = (
        ('no','no'), ('yes','yes'),
    )
        
    age = models.IntegerField()
    job= models.CharField(max_length = 100,choices = JOB, default = 'unknown', blank = False )
    marital = models.CharField(max_length = 100,choices = MARTIAL, default = 'single', blank = False )
    education = models.CharField(max_length = 100,choices = EDUCATION, default = 'unknown', blank = False )
    default = models.CharField(max_length = 100,choices = DEFAULT, default = 'no', blank = False )
    balance = models.IntegerField()
    housing = models.CharField(max_length = 100,choices = HOUSING, default = 'no', blank = False )
    loan = models.CharField(max_length = 100,choices = LOAN, default = 'no', blank = False )
    contact = models.CharField(max_length = 100,choices = CONTACT, default = 'unknown', blank = False )
    day = models.IntegerField()
    month = models.CharField(max_length = 100,choices = MONTH, default = 'may', blank = False )
    duration = models.IntegerField()
    campaign = models.IntegerField()
    pdays = models.IntegerField()
    previous= models.IntegerField()
    poutcome= models.CharField(max_length = 100,choices = POUTCOME, default = 'unknown', blank = False )
    y= models.CharField(max_length = 100,choices = Y, default = 'no', blank = False )
    


class Predictions(models.Model):

    JOB=(
        ('management','management'), ('technician','technician'),
        ('entrepreneur','entrepreneur'), ('blue-collar','blue-collar'),
        ('unknown','unknown'), ('retired','retired'), ('admin.','admin.'),
        ('services','services'),('self-employed','self-employed'),('unemployed','unemployed'),
        ('housemaid','housemaid'),('student', 'student'),
    )
    MARTIAL= (
        ('married','married'),('single','single'), ('divorced','divorced'),
    )
    EDUCATION = (
        ('tertiary','tertiary'),('secondary','secondary'),('unknown','unknown'), (  'primary',  'primary'),
    )
    DEFAULT = (
        ('no','no'), ('yes','yes'),
    )
    HOUSING = (
        ('no','no'), ('yes','yes'),
    )
    LOAN = (
        ('no','no'), ('yes','yes'),
    )
    CONTACT=(
        ('unknown','unknown'),('cellular','cellular'),('telephone','telephone'),  
    )
    MONTH= (
        ('may','may'),('jun','jun'),('jul','jul'),('aug','aug'),('oct','oct'),('nov','nov'),
        ('dec','dec'),('jan','jan'),('feb','feb'),('mar','mar'),('apr','apr'),('sep','sep'),
    )
    POUTCOME = ( 
        ('unknown','unknown'),('failure','failure'),('other','other'), ('success','success')
    )
    Y = (
        ('no','no'), ('yes','yes'),
    )
        
    age = models.IntegerField()
    job= models.CharField(max_length = 100,choices = JOB, default = 'unknown', blank = False )
    marital = models.CharField(max_length = 100,choices = MARTIAL, default = 'single', blank = False )
    education = models.CharField(max_length = 100,choices = EDUCATION, default = 'unknown', blank = False )
    default = models.CharField(max_length = 100,choices = DEFAULT, default = 'no', blank = False )
    balance = models.IntegerField()
    housing = models.CharField(max_length = 100,choices = HOUSING, default = 'no', blank = False )
    loan = models.CharField(max_length = 100,choices = LOAN, default = 'no', blank = False )
    contact = models.CharField(max_length = 100,choices = CONTACT, default = 'unknown', blank = False )
    day = models.IntegerField()
    month = models.CharField(max_length = 100,choices = MONTH, default = 'may', blank = False )
    duration = models.IntegerField()
    campaign = models.IntegerField()
    pdays = models.IntegerField()
    previous= models.IntegerField()
    poutcome= models.CharField(max_length = 100,choices = POUTCOME, default = 'unknown', blank = False )
    probability = models.FloatField(default = 0,blank=True)
    y= models.CharField(max_length = 100,choices = Y, default = 'No', blank = True,  )

# class MyCsvModel(CsvModel):
#      class Meta:
#         dbModel = BankModel
#         delimiter = ";"

artificial_demo/webapp/forms.py
from django import forms
from django.forms import FloatField
from django.contrib.auth.forms import UserCreationForm
from django.core.validators import MinValueValidator, MaxValueValidator
from .models import BankModel,Predictions

class UploadFileForm(forms.Form):
    file = forms.FileField()


class CustomerForm(forms.ModelForm):
    
    class Meta:

        model = Predictions

        #fields = '__all__'
        fields = ['age','job', 'marital', 'education', 'default', 'balance', 'housing','loan', 'contact', 'day', 'month', 'duration','campaign','pdays','previous','poutcome']
        # labels = {
        #     'term': _('Loan term'),
        # }
        # help_texts = {
        #     'term': _('Choose the term of your loan'),
        # }
        # error_messages = {
        #     'loan_amnt': {
        #         'max_length': _("Maximum loan amount allowed is 35000."),
        #     },
        # }

artificial_demo/webapp/views.py
from django.shortcuts import render
from rest_framework.decorators import api_view
from urllib.parse import urlencode
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import render,redirect
from django.template import RequestContext
from .forms import UploadFileForm, CustomerForm
from .models import BankModel,Predictions
from django.contrib import messages
import csv
import io
from io import StringIO
import pandas as pd
import os
from django_pandas.io import read_frame
from .machine_learning import ML
import numpy as np


def prediction_list(request):
    template='ml/prediction_list.html'

    predictions = Predictions.objects.all().order_by('-pk')
    args = {'predictions':predictions}
    # decision_buttons(request)

    return render(request, template, args)


def predict(data):
    clf = ML()
    df = clf.df.drop(["id"],axis=1)
    new_df=df.append(data).reset_index()
    print("---------------FORM IS NOT VALID")
    print(new_df.shape)

    clf.pre_process(new_df)

    y_pred, y_proba = clf.predict()

    prediction = Predictions.objects.latest("pk")
    prediction.y = "No" if y_pred[0] == 0 else "Yes"
    prediction.probability = np.round(float(y_proba[0][1]), decimals=2)
    prediction.save()


def prediction_new(request):
    template='ml/prediction_form.html'

    if request.method == 'POST':
        form = CustomerForm(request.POST)
        if form.is_valid():
            form.save()

            columns = form.data.keys()
            new_df = pd.DataFrame(pd.DataFrame(form.data.values()).values.reshape(1,-1)).drop(0,axis=1)
            new_df.columns=list(columns)[1:]
            num_col= ["age","balance","day","duration","campaign","pdays","previous"]
            new_df[num_col] = new_df[num_col].apply(pd.to_numeric)
            new_df["y"] = "no"
            
            predict(new_df)

            # form.initial({"probability":y_proba})
            # form.data["probability"] = y_proba
            # form.data["y"] = y_pred

            
            return redirect('predictions')
        else:
            print("---------------FORM IS NOT VALID")
            print(form.errors)
            args = {'form':form, 'errors':form.errors}
            return render(request, template, args)
    else:
        form = CustomerForm()
        args = {'form':form}
        return render(request, template, args)


def reset_BankModel(request):
    print("####### RESETING ###########")
    print(request)

    if len(BankModel.objects.all()) !=0:
        BankModel.objects.all().delete()

    request.session['updated'] = False

    request.session['acc'] = "--"
    request.session['prec'] = "--"
    request.session['rec'] = "--"
    request.session['f1'] = "--"
    request.session['auc'] ="--"

    request.session['acc_cv'] = "--"
    request.session['prec_cv'] = "--"
    request.session['rec_cv'] = "--"
    request.session['f1_cv'] = "--"
    request.session['auc_cv'] = "--"
    return redirect("/artificial_demo/machine-learning")


def train_evaluate(requset):
    clf=ML()
    clf.train()

    acc,prec,rec,f1,auc =   clf.evaluate() 
    requset.session['acc'] = "{0:.2f}%".format(acc)
    requset.session['prec'] = "{0:.2f}%".format(prec)
    requset.session['rec'] = "{0:.2f}%".format(rec)
    requset.session['f1'] = "{0:.2f}%".format(f1)
    requset.session['auc'] = "{0:.2f}%".format(auc)

    acc,prec,rec,f1,auc =   clf.cross_val_score() 
    requset.session['acc_cv'] = "{0:.2f}%".format(acc)
    requset.session['prec_cv'] = "{0:.2f}%".format(prec)
    requset.session['rec_cv'] = "{0:.2f}%".format(rec)
    requset.session['f1_cv'] = "{0:.2f}%".format(f1)
    requset.session['auc_cv'] = "{0:.2f}%".format(auc)
    
    return redirect("/artificial_demo/machine-learning")




@api_view(['GET', 'POST'])
def upload_file(request):

    #ml_model = ML()
    #ml_model.train()
    # print(ml_model.evaluate())




    template_form='ml/dataset_form.html'

    form = UploadFileForm()
    args = {'form':form}

    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():

            csv_file = (request.FILES["file"])   
            #Return error messages when user upload wrong files
            if not csv_file.name.endswith('.csv'):
                messages.error(request, "Please upload a csv file",fail_silently=True)
                return render(request, template_form, args)
            else:
                print("#### Updating Bank Table")
                update_BankModel(csv_file)
                args["file_name"] =csv_file
                request.session['updated'] = True
                messages.success(request,'Your have uploaded ' +  str(csv_file) +  ' successfully!')
                return render(request, template_form, args)


        else: #When form is not valid render the upload form again
            return render(request, template_form, args)
    else:     #When its GET request render the upload form
        return render(request, template_form, args)




    
def update_BankModel(csv_file):
    df= pd.read_csv(csv_file, sep=";")    
    df_records = df.to_dict('records')

    model_instances = [BankModel(
        age=record['age'],
        job=record['job'],
        marital=record['marital'],
        education=record['education'],
        default=record['default'],
        balance=record['balance'],
        housing=record['housing'],
        loan=record['loan'],
        contact=record['contact'],
        day=record['day'],
        month=record['month'],
        duration=record['duration'],
        campaign=record['campaign'],
        pdays=record['pdays'],
        previous=record['previous'],
        poutcome=record['poutcome'],
        y=record['y']
    ) for record in df_records]

    BankModel.objects.bulk_create(model_instances)

def list_dataset(request):
    template='ml/dataset_list.html'

    data = BankModel.objects.all()
    args = {'data':data}
    #decision_buttons(request)    
    return render(request, template, args)

    # data_set = csv_file.read().decode('UTF-8')
    # io_string = io.StringIO(data_set)
    # next(io_string) # skip the first line of the file sicne its the header
    # for column in csv.reader(io_string, delimiter=';'):
    #     _,created = BankModel.objects.update_or_create(
    #         age = column[0],
    #         job = column[1],
    #         marital = column[2],
    #         education = column[3],
    #         default = column[4],
    #         balance = column[5],
    #         housing = column[6],
    #         loan = column[7],
    #         contact = column[8],
    #         day = column[9],
    #         month = column[10],
    #         duration = column[11],
    #         campaign = column[12],
    #         pdays = column[13],
    #         previous = column[14],
    #         poutcome = column[15],
    #         y = column[16],

    #     )

artificial_demo/webapp/templates/ml/dataset_list.html
{% extends 'base.html' %}

{%block head%}
<script>
//   window.setTimeout(function () {
//     location.href = "http://127.0.0.1:8001/workflow/loan/";
// }, 15000);
  </script>
<title>Data List</title>
{% endblock %}


{%block body %}
 <div class="container">
        <div class="row">
            <!-- <div class="col-lg-8"> -->
              
            <hr>
            <a href="http://google.com" class="button">Go to Google</a>

            <button onclick="location.location='/artificial_demo/reset_table'" class="btn-block btn-danger">Delete Table</button>

            <table class="table  table-hover table-striped">
                    <thead class="table-dark">
                      <tr style='white-space: nowrap' class="text-center">
                        <th scope="col">Loan ID</th>
                        <th scope="col">Date</th>
                        <th scope="col">Customer ID</th>
                        <th scope="col">Loan amount</th>
                        <th scope="col">Purpose</th>
                        <th scope="col">Status</th>
                        <th scope="col">Pay on time(%)</th>
                        <!-- <th scope="col">ML decision</th> -->
                        <th scope="col">Decision</th>
                      </tr>
                    </thead>
                    <tbody>
                      
                        {% for result in data %}
                        <tr>
                            <td>{{ result.id }}</td>
                            <td>{{ result.y }}</td>
                            <!-- <td >{{ result.owner }}</td>
                            <td>{{ result.loan_amnt }}</td>
                            <td>{{ result.purpose }}</td>
                            <td>{{result.status }} </td> -->

                            <!-- <td>{{result.default_prob |floatformat:2  }}</td>
                            <td style='white-space: nowrap'>
                              {% ifequal "Prediction completed" result.status %}

                              <form method="get">

                                <button type="submit"  value="{{ result.id }}" class="btn btn-success" name="acc_btn">Accept</button>
                                <button type="submit"  value="{{ result.id }}" class="btn btn-danger" name="dec_btn">Decline</button>

                               </form> 

                              {% else %}
                                {% if "Issued" == result.decision %}
                                <font color="green"><b>{{result.decision}}</b></font>
                                {% elif  "Declined" == result.decision %}
                                <font color="Red"><b>{{result.decision}}</b></font>
                                {% endif %}
                              {% endifequal %}
                            </td>-->
                        
                        </tr>
                        {% endfor %}
                        
                    </tbody>

            </table>
  


            <!-- </div> -->
        </div>
</div>


  
{% endblock %}

artificial_demo/webapp/templates/ml/prediction_form.html
{% extends 'base.html' %}



{%block head%}
<style>
    .card-body {
  background-color:#f9fafc;
  padding: 0 90px;
}
label{
    font-weight: bold;
    font-weight: bold;
}
    .form-group.required .control-label:after {
  content:"*";
  color:red;
}
</style>
{% endblock %}

{% block body %}
<div class='container'>
    {% if form.errors %}
        <div class="alert alert-{{ message.tags }}">{{ form.errors }}</div>
    {% endif %}

    
    <form method="post">

        <!-- {% if form.errors %}
            {% for field in form %}
                {% for error in field.errors %}
                    <div class="alert alert-danger">
                        <strong>{{ error|escape }}</strong>
                    </div>
                {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endif %} -->
        {% csrf_token %}

        <br>
        <div class="card text">
                <div class="card-header">
                <h3>New customer form</h3>

                  Please fill up this form to register a new customer and get the subscription prediction
                </div>
            <div class="card-body">  

<!-- 1st row -->
<hr>

            <div class="form-row">

              <div class="form-group col-md-3">
                <label for="id_loan_amnt required">Age</label>
                <input type="number" name="age"  class="form-control" step="any"  required id="id_age">
              </div>
              <div class="form-group col-md-3">
                <label for="balance">Balance</label>
                <input type="number" name="balance"  step="any" required id="id_balance" class="form-control" >
              </div>
              <div class="form-group col-md-3">
                    <label for="id_day required">Day</label>
                    <input type="number" name="day"  step="any" required id="id_day" class="form-control" >

                    <!-- <select name="month" id="month" class="form-control">
                            <option value= 1 selected>1</option>
                            <option value=2>2</option>
                            <option value=3>3</option>
                            <option value=4>4</option>
                            <option value=5>5</option>
                            <option value=6>6</option>
                            <option value=7>7</option>
                            <option value=8>8</option>
                            <option value=9>9</option>
                            <option value=10>10</option>
                            <option value=11>11</option>
                            <option value=12>12</option>
                            <option value=13>13</option> 
                            <option value=14>14</option> 
                            <option value=15>15</option> 
                            <option value=16>16</option> 
                            <option value=17>17</option> 
                            <option value=18>18</option> 
                            <option value=19>19</option> 
                            <option value=20>20</option>
                            <option value=21>21</option>
                            <option value=22>22</option>
                            <option value=23>23</option>
                            <option value=24>24</option>
                            <option value=25>25</option>
                            <option value=26>26</option>
                            <option value=27>27</option>
                            <option value=28>28</option>
                            <option value=29>29</option>
                            <option value=30>30</option>
                            <option value=31>31</option>
                    </select> -->
              </div>
              <div class="form-group col-md-3">
                    <label for="month">Month</label>
                    <select name="month" id="month" class="form-control">
                            <option value="jan" selected>Jannuary</option>
                            <option value="feb">February</option>
                            <option value="mar">March</option>
                            <option value="apr">April</option>
                            <option value="may">May</option>
                            <option value="jun">June</option>
                            <option value="jul">July</option>
                            <option value="aug">August</option>
                            <option value="sep">September</option>
                            <option value="oct">October</option>
                            <option value="nov">November</option>
                            <option value="dec">December</option>    
                    </select>
                  </div>


            </div>
<!-- 2nd row -->
<hr>

            <div class="form-row">
                    <div class="form-group col-md-3">
                            <label for="marital">Marital</label>
                            <select name="marital" id="marital" class="form-control">
                                    <option value="married" selected>married</option>
                                    <option value="single">single</option>
                                    <option value="divorced">divorced</option>
                            </select>

                    </div>
                    <div class="form-group col-md-3">
                            <label for="education">Education</label>
                            <select name="education" id="education" class="form-control">
                                    <option value="secondary" selected>secondary</option>
                                    <option value="primary">primary</option>
                                    <option value="unknown">unknown</option>
                            </select>

                    </div>
                    <div class="form-group col-md-3">
                            <label for="default">Default</label>
                            <select name="default" id="default" class="form-control">
                                    <option value="no" selected>no</option>
                                    <option value="yes">yes</option>
                            </select>
                    </div>
                    <div class="form-group col-md-3">
                            <label for="housing">Housing</label>
                            <select name="housing" id="housing" class="form-control">
                                    <option value="no" selected>no</option>
                                    <option value="yes">yes</option>
                            </select>
                    </div>
            </div>
<!-- 3rd row -->
<hr>

            <div class="form-row">
                    <div class="form-group col-md-3">
                            <label for="loan">Loan</label>
                            <select name="loan" id="loan" class="form-control">
                                    <option value="no" selected>no</option>
                                    <option value="yes">yes</option>
                            </select>
                    </div>
                    <div class="form-group col-md-3">
                            <label for="contact">Contact</label>
                            <select name="contact" id="contact" class="form-control">
                                    <option value="cellular" selected>cellular</option>
                                    <option value="telephone">telephone</option>
                                    <option value="unknown">unknown</option>
                            </select>
                    </div>
                    <div class="form-group col-md-3">
                            <label for="poutcome">Poutcome</label>
                            <select name="poutcome" id="poutcome" class="form-control">
                                    <option value="failure" selected>failure</option>
                                    <option value="success">success</option>
                                    <option value="other">other</option>
                                    <option value="unknown">unknown</option>
                            </select>
                    </div>
                    <div class="form-group col-md-3">
                            <label for="term">Job</label>
                            <select name="job" id="job" class="form-control">
                                    <option value="management" selected>Management</option>
                                    <option value="technician">Technician</option>
                                    <option value="entrepreneur">Entrepreneur</option>
                                    <option value="blue-collar">60 Blue-collar</option>
                                    <option value="retired">Retired</option>
                                    <option value="admin.">Admin</option>
                                    <option value="services">Services</option>
                                    <option value="self-employed">Self-employed</option>
                                    <option value="unemployed">Unemployed</option>
                                    <option value="housemaid">Housemaid</option>
                                    <option value="student">Student</option>
            
                                    <option value="unknown">Unknown</option>
            
                            </select>
                          </div>
            </div>
<!-- 4th row-->
            <hr>
            <div class="form-row">

                    <div class="form-group col-md-3">
                      <label for="id_duration required">Duration</label>
                      <input type="number" name="duration"  class="form-control" step="any"  required id="id_duration">
                    </div>

                    <div class="form-group col-md-3">
                      <label for="campaign">Campaign</label>
                      <input type="number" name="campaign"  step="any" required id="id_campaign" class="form-control" >
                    </div>
                    <div class="form-group col-md-3">
                            <label for="pdays">Pdays</label>
                            <input type="number" name="pdays"  step="any" required id="id_pdays" class="form-control" >
                    </div>
                    <div class="form-group col-md-3">
                            <label for="previous">Previous</label>
                            <input type="number" name="previous"  step="any" required id="id_previous" class="form-control" >
                    </div>
            </div>

            <hr>
            <button class="btn btn-primary" type='submit'>Submit</button>
            
        </div>

    <br>
</div>
</form>
</div>

{% endblock %}

artificial_demo/webapp/templates/ml/prediction_list.html
{% extends 'base.html' %}

{%block head%}
<script>
//   window.setTimeout(function () {
//     location.href = "http://127.0.0.1:8001/workflow/loan/";
// }, 15000);
  </script>
<title>Predictions</title>
{% endblock %}


{%block body %}

 <div class="container">
     <br>
     <h3>Prediction Results</h3>
        <p>For simplicity only few features of the user are illustrated in this table</p>
        <hr>
        <div class="row">
            <!-- <div class="col-lg-8"> -->
              
            <hr>
            
            <table class="table  table-hover table-striped">
                    <thead class="table-dark">
                      <tr style='white-space: nowrap' class="text-center">
                        <th scope="col">ID</th>
                        <th scope="col">Age</th>
                        <th scope="col">Marital</th>
                        <th scope="col">Education</th>
                        <th scope="col">Default</th>
                        <th scope="col">Loan</th>
                        <th scope="col">Likelyhood</th>
                        <th scope="col">Decision</th>
                      </tr>
                    </thead>
                    <tbody>
                      
                        {% for result in predictions %}
                        <tr class="text-center" >
                            <td>{{ result.id }}</td>
                            <td>{{ result.age }}</td>
                            <td >{{ result.marital }}</td>
                            <td>{{ result.education }}</td>
                            <td>{{ result.default }}</td>
                            <td>{{result.loan }} </td>
                            <td>{{ result.probability }}</td>
                            <td>{{result.y }} </td>
                            <!-- <td>{{result.ml_decision }} </td> -->
                            <td style='white-space: nowrap'>
                              {% ifequal "Prediction completed" result.status %}

                              <form method="get">

                                <button type="submit"  value="{{ result.id }}" class="btn btn-success" name="acc_btn">Accept</button>
                                <button type="submit"  value="{{ result.id }}" class="btn btn-danger" name="dec_btn">Decline</button>

                               </form>
                              {% else %}
                                {% if "Issued" == result.decision %}
                                <font color="green"><b>{{result.decision}}</b></font>
                                {% elif  "Declined" == result.decision %}
                                <font color="Red"><b>{{result.decision}}</b></font>
                                {% endif %}
                              {% endifequal %}
                            </td>
                        
                        </tr>
                        {% endfor %}
                        
                    </tbody>

            </table>
  


            <!-- </div> -->
        </div>
</div>


  
{% endblock %}